server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: ManagementCenter
          uri: http://localhost:8082
          predicates:
            - Path=/managementCenters/** 
        - id: Installation
          uri: http://localhost:8083
          predicates:
            - Path=/installations/**
        - id: orderstatus
          uri: http://localhost:8084
          predicates:
            - Path=/orderStatuses/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Order
          uri: http://Order:8080
          predicates:
            - Path=/orders/** 
        - id: ManagementCenter
          uri: http://ManagementCenter:8080
          predicates:
            - Path=/managementCenters/** 
        - id: Installation
          uri: http://Installation:8080
          predicates:
            - Path=/installations/** 
        - id: orderstatus
          uri: http://orderstatus:8080
          predicates:
            - Path=/orderStatuses/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
